import type { Rng } from "./rng";
import { createSpeedTrialEngine, type Problem, type SpeedTrialConfig, SPEED_TRIAL_DEFAULTS } from "./speed-trial";

/**
 * Chalkboard Challenge — two expressions, pick the larger.
 *
 * The comparison is the exercise, not the arithmetic: you evaluate one side,
 * hold that number, evaluate the other, then compare. So the generator's job is
 * to keep both sides *individually* easy while making the comparison
 * non-obvious, which means the two values must land close together. Sides that
 * differ by a mile can be called from a glance at the operands and train
 * nothing.
 */

export type Op = "+" | "−" | "×" | "÷";

export interface Expression {
  left: number;
  right: number;
  op: Op;
  value: number;
}

export interface ChalkboardData {
  a: Expression;
  b: Expression;
}

/** Answer indices, matching the three buttons the play screen renders. */
export const CHALK_LEFT = 0;
export const CHALK_EQUAL = 1;
export const CHALK_RIGHT = 2;

function evaluate(left: number, right: number, op: Op): number {
  switch (op) {
    case "+":
      return left + right;
    case "−":
      return left - right;
    case "×":
      return left * right;
    case "÷":
      return left / right;
  }
}

/** Operator mix widens with level: addition first, division only once it is earned. */
function opsForLevel(level: number): Op[] {
  if (level <= 2) return ["+", "−"];
  if (level <= 5) return ["+", "−", "×"];
  return ["+", "−", "×", "÷"];
}

function buildExpression(rng: Rng, level: number, op: Op): Expression {
  const span = Math.min(12 + level * 4, 60);

  if (op === "÷") {
    // Built from the answer so it divides exactly — a fractional side turns a
    // comparison into a question about notation.
    const divisor = rng.range(2, Math.min(9, 2 + level));
    const quotient = rng.range(2, Math.max(3, Math.round(span / divisor)));
    return { left: divisor * quotient, right: divisor, op, value: quotient };
  }

  if (op === "×") {
    const left = rng.range(2, Math.min(12, 3 + level));
    const right = rng.range(2, Math.min(12, 3 + level));
    return { left, right, op, value: left * right };
  }

  if (op === "−") {
    const left = rng.range(Math.ceil(span / 2), span);
    const right = rng.range(1, left - 1);
    return { left, right, op, value: left - right };
  }

  const left = rng.range(1, span);
  const right = rng.range(1, span);
  return { left, right, op, value: left + right };
}

/**
 * Build a second expression whose value sits within `gap` of the first, so the
 * player has to actually compute rather than eyeball. Falls back to whatever it
 * managed if the search does not converge, which keeps generation bounded.
 */
function buildNear(rng: Rng, level: number, target: number, gap: number, ops: Op[]): Expression {
  let best: Expression | null = null;
  for (let attempt = 0; attempt < 40; attempt++) {
    const candidate = buildExpression(rng, level, rng.pick(ops));
    if (candidate.value < 0) continue;
    const distance = Math.abs(candidate.value - target);
    if (distance <= gap) return candidate;
    if (!best || distance < Math.abs(best.value - target)) best = candidate;
  }
  return best ?? buildExpression(rng, level, ops[0]!);
}

export function generateChalkboard(rng: Rng, level: number): Problem<ChalkboardData> {
  const ops = opsForLevel(level);
  const a = buildExpression(rng, level, rng.pick(ops));

  // Roughly one trial in seven is a genuine tie, which is what makes the Equal
  // button a real option rather than decoration.
  if (rng.bool(0.14)) {
    for (let attempt = 0; attempt < 60; attempt++) {
      const b = buildExpression(rng, level, rng.pick(ops));
      if (b.value === a.value) return { data: { a, b }, answer: CHALK_EQUAL };
    }
  }

  // The window narrows with level, so the two sides converge as you improve.
  const gap = Math.max(1, Math.round(10 - level * 0.7));
  let b = buildNear(rng, level, a.value, gap, ops);

  // A tie generated by accident here would be scored as a side, so nudge it —
  // by a step that keeps the expression whole. Adding 1 to the numerator of a
  // division would leave a fraction, so division moves by a whole divisor.
  if (b.value === a.value) {
    const step = b.op === "÷" ? b.right : 1;
    b = { ...b, left: b.left + step, value: evaluate(b.left + step, b.right, b.op) };
  }
  if (b.value === a.value) return { data: { a, b }, answer: CHALK_EQUAL };

  return { data: { a, b }, answer: a.value > b.value ? CHALK_LEFT : CHALK_RIGHT };
}

export const CHALKBOARD_DEFAULTS: SpeedTrialConfig = {
  ...SPEED_TRIAL_DEFAULTS,
  gameId: "chalkboard",
  durationSec: 90,
  startMs: 6000,
  minMs: 1600,
};

export const chalkboardEngine = createSpeedTrialEngine<ChalkboardData>((rng, level) =>
  generateChalkboard(rng, level),
);
