import type { GameCategory, GameId, GameMeta } from "./types";

/**
 * The exercise registry. Everything that enumerates games — the dashboard grid,
 * the sidebar, the stats page, the sitemap — reads from here, so adding a game
 * is one entry plus an engine rather than an edit in six places.
 */
export const GAMES: GameMeta[] = [
  {
    id: "n-back",
    name: "N-Back",
    tagline: "Track what appeared N steps ago",
    category: "training",
    trains: ["Working memory", "Fluid reasoning", "Attention control"],
    about:
      "The n-back task is the most studied working-memory exercise there is. A stream of stimuli arrives one at a time and you report whether the current one matches the one N steps back. Because the answer changes with every new item, you cannot rehearse a fixed list — you have to continuously update what you are holding, which is precisely the capacity the task trains.",
    how: [
      "A stimulus appears every few seconds — a square in a grid, a spoken letter, a colour, a shape.",
      "Press the key for a modality when the current stimulus matches the one N steps earlier.",
      "Say nothing when it does not match. Staying silent is a real answer and is scored.",
      "Score 90% or better and N goes up next block; below 70% and it comes back down.",
    ],
    origin: "Kirchner (1958); popularised for training by Jaeggi et al. (2008)",
    metricLabel: "N level",
    icon: "grid",
    accentVar: "--stim-1",
    hasTutorial: true,
    minutes: 8,
  },
  {
    id: "complex-working-memory",
    name: "Complex Working Memory",
    tagline: "Remember a sequence while judging symmetry",
    category: "training",
    trains: ["Working memory", "Interference control", "Task switching"],
    about:
      "A complex span task: memorising is interleaved with an unrelated decision, so you cannot quietly rehearse between items. Holding a growing list while something else keeps demanding your attention is much closer to how working memory is actually used than any pure recall task.",
    how: [
      "A pattern appears — decide whether it is symmetric about its vertical axis.",
      "A cell in the grid then lights briefly. Remember it, and where it fell in the order.",
      "The two alternate for as many rounds as the current level demands.",
      "Recall the cells in the order they appeared. Two perfect trials promote you; two failures demote you.",
    ],
    origin: "Symmetry span; Unsworth, Heitz, Schrock & Engle (2005)",
    metricLabel: "Set size",
    icon: "layers",
    accentVar: "--stim-5",
    hasTutorial: true,
    minutes: 7,
  },
  {
    id: "memory-span",
    name: "Memory Span",
    tagline: "Hold a growing sequence in mind",
    category: "training",
    trains: ["Short-term memory", "Verbal encoding", "Attention"],
    about:
      "The classic span task. Items appear one after another and you repeat them back. Each success adds one item, until you reach the length where your memory gives out — that length is your span. Reverse mode asks for the sequence backwards, which turns simple storage into manipulation and is reliably harder.",
    how: [
      "Digits (or letters) flash one at a time.",
      "Type them back in order — or in reverse, if reverse mode is on.",
      "Get it right and the sequence grows by one.",
      "Two failures at the same length end the run. Your longest correct sequence is your span.",
    ],
    origin: "Digit span; Jacobs (1887), and a subtest of every major IQ battery since",
    metricLabel: "Span",
    icon: "sequence",
    accentVar: "--stim-3",
    hasTutorial: true,
    minutes: 5,
  },
  {
    id: "corsi",
    name: "Corsi Block-Tapping",
    tagline: "Repeat the sequence of blocks",
    category: "training",
    trains: ["Visuospatial memory", "Sequencing", "Attention"],
    about:
      "The spatial counterpart to digit span. Nine blocks sit in a deliberately irregular arrangement — irregular so you cannot fall back on a tidy verbal description like 'top row, left to right'. They light in sequence and you tap them back. Most healthy adults land somewhere between five and seven.",
    how: [
      "Watch the blocks light up one after another.",
      "Tap them back in the same order — or in reverse, in reverse mode.",
      "Each success adds one block to the sequence.",
      "Two failures at the same length end the run.",
    ],
    origin: "Corsi (1972)",
    metricLabel: "Block span",
    icon: "blocks",
    accentVar: "--stim-6",
    hasTutorial: true,
    minutes: 5,
  },
  {
    id: "pasat",
    name: "PASAT",
    tagline: "Add each number to the one before it",
    category: "training",
    trains: ["Processing speed", "Working memory", "Sustained attention"],
    about:
      "Paced Auditory Serial Addition. Numbers arrive at a fixed rhythm that does not wait for you, and each answer must be added to the number before it — not to your running total. The moment you slip, the next item is already arriving, which is what makes this the most demanding exercise here.",
    how: [
      "A digit is spoken (or shown) every few seconds.",
      "Add it to the digit immediately before it, and answer with that sum.",
      "Do not keep a running total. Each sum uses only the last two digits.",
      "Answer accurately and the pace quickens. Miss too many and it eases back.",
    ],
    origin: "Gronwall (1977)",
    metricLabel: "Correct sums",
    icon: "pulse",
    accentVar: "--stim-4",
    hasTutorial: true,
    minutes: 4,
  },
  {
    id: "mental-math",
    name: "Mental Math",
    tagline: "Arithmetic in your head, against the clock",
    category: "training",
    trains: ["Numerical fluency", "Processing speed", "Working memory"],
    about:
      "Addition, subtraction, multiplication and division, with no pen and no calculator. Difficulty is tracked separately for each side of the problem, so if three-digit multipliers are what slows you down, that is the side that stays put while the other keeps growing.",
    how: [
      "A problem appears. Solve it in your head and type the answer.",
      "Speed counts as well as accuracy.",
      "Each operand has its own digit-length level, and they move independently.",
      "Mix mode shuffles all four operations so you cannot anticipate the next one.",
    ],
    origin: "Standard arithmetic fluency training",
    metricLabel: "Correct",
    icon: "calculator",
    accentVar: "--stim-2",
    hasTutorial: false,
    minutes: 5,
  },
  {
    id: "decoder",
    name: "Decoder",
    tagline: "Spot the sequence hidden in the stream",
    category: "speed",
    trains: ["Sustained attention", "Working memory", "Vigilance"],
    about:
      "Digits arrive one after another, fast, and almost all of them are noise. Buried in the stream are three-digit runs that step up by two — 2-4-6, 3-5-7, 4-6-8 — and your job is to catch them as they complete. The difficulty is not any single digit; it is that nothing ever pauses, so you have to hold the last two while judging the next, for minutes at a stretch.",
    how: [
      "Digits from 2 to 9 appear one at a time, roughly a hundred a minute.",
      "Watch for a run of three that climbs by two: 2-4-6, 3-5-7 or 4-6-8.",
      "Respond as the third digit lands. You have a short window before it stops counting.",
      "Most digits are noise. Responding to them costs you.",
    ],
    origin: "Rapid Visual Information Processing; Wesnes & Warburton (1984)",
    metricLabel: "Sequences caught",
    icon: "stream",
    accentVar: "--stim-1",
    hasTutorial: true,
    minutes: 5,
  },
  {
    id: "chalkboard",
    name: "Chalkboard Challenge",
    tagline: "Which side is worth more?",
    category: "speed",
    trains: ["Quantitative reasoning", "Working memory", "Processing speed"],
    about:
      "Two expressions, side by side. Pick the larger one — or call them equal. The trick is that you cannot evaluate both at once: you work out one side, hold that number while you work out the other, then compare. That hold-and-compare step is the whole exercise, and it is why the difficulty rises faster than the arithmetic alone would suggest.",
    how: [
      "Two expressions appear. Decide which has the greater value.",
      "Tap that side, or tap Equal when they match.",
      "A run of correct answers raises your multiplier; a wrong one knocks it back.",
      "Answer before the timer runs out, and the timer keeps shortening.",
    ],
    origin: "Quantitative comparison, as popularised by Lumosity",
    metricLabel: "Score",
    icon: "scales",
    accentVar: "--stim-2",
    hasTutorial: false,
    minutes: 4,
  },
  {
    id: "perilous-path",
    name: "Perilous Path",
    tagline: "Retrace the route without hitting a hazard",
    category: "speed",
    trains: ["Visuospatial memory", "Route planning", "Inhibition"],
    about:
      "A path is drawn across a grid, and hazards are scattered around it. Both vanish. Now walk the route back from memory — and in reverse mode, walk it backwards, which means holding the whole route rather than following it a step at a time. The hazards are the cruel part: remembering where the path went is not enough if you cannot also remember what to avoid.",
    how: [
      "Watch the route light up square by square, and note the hazards.",
      "Everything disappears.",
      "Tap the squares of the route in order, moving one step at a time.",
      "Step on a hazard and the run ends. Two failures at a length end the session.",
    ],
    origin: "Spatial route learning, in the tradition of the Austin Maze",
    metricLabel: "Path length",
    icon: "path",
    accentVar: "--stim-3",
    hasTutorial: true,
    minutes: 6,
  },
  {
    id: "double-decision",
    name: "Double Decision",
    tagline: "Name the centre, place the edge",
    category: "speed",
    trains: ["Visual processing speed", "Useful field of view", "Divided attention"],
    about:
      "Two things flash at once and both matter: a vehicle at the centre, and a road sign somewhere out at the edge. Report what the vehicle was and where the sign appeared. As you improve the flash gets shorter — down towards a couple of hundredths of a second — and the sign drifts further out, widening the region of vision your brain can actually use at a glance.",
    how: [
      "Fix your eyes on the centre of the screen and keep them there.",
      "A vehicle flashes in the middle while a sign flashes out at the edge, among distractors.",
      "Say which vehicle it was, then point to where the sign appeared.",
      "Get both right and the next flash is shorter, and the sign moves further out.",
    ],
    origin: "Useful Field of View; Ball & Owsley, as used in the ACTIVE trial",
    metricLabel: "Flash",
    icon: "eye",
    accentVar: "--stim-4",
    hasTutorial: true,
    minutes: 6,
  },
  {
    id: "processing",
    name: "Processing",
    tagline: "Read faster than you can say the words",
    category: "speed",
    trains: ["Reading speed", "Semantic processing", "Comprehension"],
    about:
      "Words appear one at a time, in the same spot, faster than you could read them aloud. Above roughly 300 words a minute the inner voice most people read with simply cannot keep up, and the only way through is to take meaning straight from the word. Then you answer a question about what you read, which is what stops the exercise becoming a staring contest.",
    how: [
      "A passage plays one word at a time, in place.",
      "Do not try to sound the words out — let them land.",
      "Answer a question about what you just read.",
      "Answer correctly and the next passage runs faster.",
    ],
    origin: "Rapid serial visual presentation; Forster (1970)",
    metricLabel: "Words per minute",
    icon: "text",
    accentVar: "--stim-5",
    hasTutorial: false,
    minutes: 5,
  },
  {
    id: "hawkeye",
    name: "Hawkeye",
    tagline: "Where were the birds?",
    category: "speed",
    trains: ["Peripheral awareness", "Visual span", "Spatial attention"],
    about:
      "Birds flash across a wide field for a fraction of a second, then vanish. Mark where they were. Because the flash is far too brief to look around in, you cannot search — you have to take the whole field in at once. Training that habit widens how much of a scene you register from a single glance.",
    how: [
      "Keep your eyes on the centre mark.",
      "Several birds flash at once, scattered across the field.",
      "Tap every place you saw one.",
      "Get them all and the next flash is shorter and the field wider.",
    ],
    origin: "Visual span and peripheral localisation training",
    metricLabel: "Flash",
    icon: "bird",
    accentVar: "--stim-6",
    hasTutorial: false,
    minutes: 5,
  },
  {
    id: "spatial-match",
    name: "Spatial Speed Match",
    tagline: "Same shape, same way up?",
    category: "speed",
    trains: ["Spatial working memory", "Mental rotation", "Processing speed"],
    about:
      "Each shape has to be compared against the one immediately before it — same form, same orientation, same cell. Since the comparison target is always the thing that just left the screen, you are constantly replacing what you hold. It is the lightest possible version of the n-back idea, run at speed rather than depth.",
    how: [
      "A shape appears in a cell, at some rotation.",
      "Decide whether it matches the shape shown just before it — form, rotation and position all have to agree.",
      "Answer yes or no before the next one arrives.",
      "The first shape of a round has nothing to compare against.",
    ],
    origin: "Speeded 1-back matching, as popularised by Lumosity",
    metricLabel: "Score",
    icon: "rotate",
    accentVar: "--stim-1",
    hasTutorial: false,
    minutes: 3,
  },
  {
    id: "agility",
    name: "Agility",
    tagline: "Is the statement actually true?",
    category: "logic",
    trains: ["Logical reasoning", "Bias suppression", "Processing speed"],
    about:
      "A comparative claim or a small algebraic statement appears, and you have moments to say whether it holds. Some are straightforward. Others are phrased to invite the wrong answer — a negation buried mid-sentence, or an ordering that reads naturally but is false. Beating those means reading what is written rather than what you expected.",
    how: [
      "A statement appears — a comparison, an ordering, or a small equation.",
      "Decide whether it is true or false.",
      "Answer before the bar empties.",
      "Correct answers shorten the bar for the next one.",
    ],
    origin: "Speeded verification, in the tradition of grammatical reasoning tests",
    metricLabel: "Score",
    icon: "logic",
    accentVar: "--stim-3",
    hasTutorial: false,
    minutes: 4,
  },
  {
    id: "error-locator",
    name: "Error Locator",
    tagline: "Find every mistake in the passage",
    category: "logic",
    trains: ["Attention to detail", "Error monitoring", "Reading"],
    about:
      "A short passage with faults planted in it — a doubled word, a misspelling, a sentence that never got its full stop. Tap each one. Reading for meaning actively works against you here, because comprehension smooths over exactly the kind of small breakage you are hunting for; you have to read the surface instead.",
    how: [
      "A passage appears with several faults planted in it.",
      "Tap every word that is wrong.",
      "Faults are doubled words, misspellings, and missing or wrong punctuation.",
      "Tapping a word that is fine costs you, so read before you tap.",
    ],
    origin: "Proofreading and error-detection tasks",
    metricLabel: "Faults found",
    icon: "magnifier",
    accentVar: "--stim-4",
    hasTutorial: false,
    minutes: 5,
  },
  {
    id: "turtle-traffic",
    name: "Turtle Traffic",
    tagline: "Steer several at once, without collisions",
    category: "logic",
    trains: ["Task switching", "Planning", "Divided attention"],
    about:
      "Several turtles, several destinations, one grid. Each moves only when you send it, so the work is deciding who to move and when — and keeping the others in mind while you deal with one. Routes cross. Two turtles arriving at the same square at the same moment is a collision, so a plan that ignores the others is not a plan.",
    how: [
      "Each turtle has a matching destination somewhere on the grid.",
      "Tap a turtle to select it, then tap where it should step.",
      "Turtles move one square at a time, and never through rocks or each other.",
      "Get them all home before the clock runs out.",
    ],
    origin: "Multi-target coordination and planning",
    metricLabel: "Turtles home",
    icon: "turtle",
    accentVar: "--stim-6",
    hasTutorial: false,
    minutes: 6,
  },
  {
    id: "cryptogram",
    name: "Cryptogram",
    tagline: "Decode a famous quote from a number cipher",
    category: "game",
    trains: ["Logic", "Pattern recognition", "Deduction"],
    about:
      "Every letter of the alphabet has been swapped for a number. A quotation sits on screen with only a few of those pairings revealed, and the rest is deduction — letter frequencies, one-letter words, the shapes of common endings. Unlike the exercises here it is untimed, which makes it the one to reach for when you want to think rather than react.",
    how: [
      "Each number stands for one letter, consistently, throughout the quote.",
      "A few pairings are given to start you off.",
      "Click a cell and type the letter you think belongs there.",
      "Conflicts are highlighted. A hint reveals one pairing, at a cost to your score.",
    ],
    origin: "Classic substitution puzzle",
    metricLabel: "Solved",
    icon: "cipher",
    accentVar: "--stim-5",
    hasTutorial: false,
    minutes: 10,
  },
];

export const GAME_BY_ID: Record<GameId, GameMeta> = Object.fromEntries(
  GAMES.map((g) => [g.id, g]),
) as Record<GameId, GameMeta>;

export const byCategory = (category: GameCategory) => GAMES.filter((g) => g.category === category);

/** The dashboard and the sidebar both read this, so the two never drift apart. */
export const GAME_SECTIONS: { category: GameCategory; title: string; hint: string }[] = [
  {
    category: "training",
    title: "Brain training",
    hint: "Research paradigms — difficulty follows your performance",
  },
  {
    category: "speed",
    title: "Processing speed & attention",
    hint: "Fast, timed, and unforgiving of a wandering eye",
  },
  {
    category: "logic",
    title: "Logical agility & executive control",
    hint: "Switching rules, catching errors, holding a plan",
  },
  { category: "game", title: "Brain games", hint: "Untimed — think rather than react" },
];

export const TRAINING_GAMES = byCategory("training");
export const CASUAL_GAMES = byCategory("game");

export function isGameId(value: string): value is GameId {
  return value in GAME_BY_ID;
}
